"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, Mail, MessageCircle, Phone, Send } from "lucide-react";
import { FormEvent, useState } from "react";

export default function GuestSupport() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); event.currentTarget.reset(); };
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 sm:px-6 sm:py-10"><div className="mx-auto w-full max-w-lg"><Link href="/" className="flex h-11 w-11 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-700 shadow-sm"><ArrowLeft size={20} /></Link><header className="mt-8"><p className="text-sm font-semibold text-sky-600">Guest help</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em]">We are here to help</h1><p className="mt-3 text-sm leading-6 text-slate-500">You can contact us about a payment or bundle delivery without creating an account.</p></header><div className="mt-6 grid grid-cols-2 gap-3"><a href="tel:+233200000000" className="flex min-h-24 flex-col justify-between rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><Phone className="text-sky-600" size={19} /><span><strong className="block text-sm">Call support</strong><small className="mt-1 block text-xs text-slate-500">+233 20 000 0000</small></span></a><a href="mailto:help@cellulite.data" className="flex min-h-24 flex-col justify-between rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><Mail className="text-sky-600" size={19} /><span><strong className="block text-sm">Email support</strong><small className="mt-1 block text-xs text-slate-500">Usually replies quickly</small></span></a></div><form onSubmit={submit} className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_18px_45px_rgba(15,23,42,0.06)] sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-sky-50 text-sky-600"><MessageCircle size={19} /></span><div><h2 className="font-semibold">Send a message</h2><p className="text-xs text-slate-500">Include your order reference if you have one.</p></div></div><label htmlFor="guest-support-message" className="sr-only">Your message</label><textarea id="guest-support-message" name="message" required rows={6} placeholder="Tell us what happened..." className="mt-5 w-full resize-none rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-sky-500 focus:ring-4 focus:ring-sky-100" /><button type="submit" className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-sky-600 text-sm font-bold text-white"><Send size={17} /> Send message</button>{sent ? <p className="mt-3 flex items-center gap-2 text-sm font-medium text-emerald-600" role="status"><CheckCircle2 size={16} /> Message received. We will contact you.</p> : null}</form><Link href="/track-order?guest=1" className="mt-5 flex items-center justify-center text-sm font-semibold text-sky-600">Track an order</Link></div></main>;
}
